### ISSUE TITLE
[Q] start on current cursor

### ISSUE THREAD

**Issue by ghost** [ggVGc/fzf_browser#5]
Thanks for this util.

But I don't like this plugin take a full screen to search through matches, Is there a way/howto let it list at current cursor/command line, the same way as type `fzf` on terminal/console?

**Comment by ggVGc** [comment]
Not in the current state, but it could be modified to use https://github.com/jhawthorn/fzy instead.
I wrote this script a long time ago, and it's quite a hacky mess, and I intend to rewrite it in something else than bash at some point, as it's proven a useful tool.
Currently it's not really extendable though, and it wouldn't make sense to do anything really before it's rewritten.

**Comment by ghost** [comment]
`fzy`? just quick glance at the sourcecode, thought that too, do you have a visible time schedule for it? I can't live without it for just grab it for one hour.

**Comment by ggVGc** [comment]
Not sure when I'll get to working on this, but now knowing someone else than me uses it, I could maybe try getting to it sooner.
The issue with using `fzy` instead of `fzf` is that the core of this tool is based around the fact `fzf` allows you to define custom keybinds for exiting, which `fzy` does not. So I'd have to think about how to work around that before I could use something other than `fzf` as the searcher

**Comment by ghost** [comment]
It's something achieved with keybinding using in fzf with git, you can check fzf wiki for it.

**Comment by ghost** [comment]
I'll take a look whether or not I can adapt it to behave like other plugins that echo the menu at prompt instead of take all screen, the redraw also a problem with this plugin, but I'm kind of rookie here.

Yesterday when I try to find out a console file manager in linux and come up with this plugin, it brings visual that native fzf doesn't do. I aslo don't like visual like `ranger`, `deer` or other-like, three panes to navigate files. I just need util that bring a first sense of folder's content (with limited output like 5-7 first subfolders or files) and then continue to navigate down to the file we want.

I think we can use `fzf` to put its menu at current prompt, it's native to fzf to echo its output at current prompt.

**Comment by ghost** [comment]
Has a bug or something else this plugin can't search for file candidate in subfolder, meaning if I have a file named `abc` in subfolder of its parent, when I'm under parent and trigger this plugin, and type `abc` to search for it, show empty result.

**Comment by ggVGc** [comment]
`ctrl-r` toggles recursive mode, which should list everything.

**Comment by ghost** [comment]
I think I'm going to re-arrange this plugin that something echo like this https://github.com/urbainvaes/fzf-marks

I really need to change this plugin's behavior that from take full screen to draw to list at current command line.

@ggVGc : any hint how to achieve?

**Comment by ghost** [comment]
@ggVGc : I'm refactoring this plugin, can you point out where is code block to setup this layout:

```
1. trigger fuzzybrowser
2. layout:
doc/  abc | def| mnt|
src / fds.c | ocn.h | arg.h |
makefile
abc
```
What will be one command to get this layout? I'm confused when looking into the code.

**Comment by ggVGc** [comment]
I am not surprised you're confused :) The code for this script is quite insane, which is why I want to rewrite it in something else than bash before doing anything more with it (but it works fine for me so far and I am short on time so not sure if that'll happen).
This is the line that generates the file listing for directories: https://github.com/ggVGc/fzf_browser/blob/master/fzf_browser.sh#L302

**Comment by ghost** [comment]
At the end, I stopped refactoring this plugin, instead I used `tree` command to quick inspect and `Ctrl-T` from fzf to quick open files. The cost of fuzzy still too high, it slow down prompt (I use my own custom and optimized zsh's prompt, & zsh's plugins, components)
